/* ─── Guess-first lesson content templates ───
 * Ported from the medinformics content-template taxonomy (concept-flow,
 * diagnose-mechanism, spot-flaw, sequence-it) and adapted to bedcoders'
 * Lesson.tsx content-section model. Draft implementation generated by the
 * local qwen3-coder-next:latest model (Ollama, localhost:11434) from a
 * spec prompt referencing the existing InteractiveGuess component for
 * style parity, then reviewed and corrected by hand for type-safety and
 * a state-management bug in SequenceIt (see below).
 *
 * Shared pedagogy: the learner commits to a choice/order BEFORE any
 * explanation is shown, gets feedback tied to their SPECIFIC choice
 * (not generic right/wrong text), and only then sees the underlying
 * concept/mechanism/flaw/correct-order revealed.
 */
import { useMemo, useState } from 'react';
import Markdown from 'react-markdown';
import { markdownComponents } from './markdownComponents';

/* ─── Shared option type ─── */
export interface FlowOption {
  label: string;
  value: string;
}

/* ══════════════════════════════════════════════════════════════
   1. ConceptFlow — classify a real example before the concept is named
   ══════════════════════════════════════════════════════════════ */
export interface ConceptFlowProps {
  scenario: string; // markdown; the real example presented first
  question: string; // plain text; what to classify
  options: FlowOption[];
  correctValue: string;
  feedback: Record<string, string>; // markdown, keyed by option value
  concept: string; // markdown; general concept, revealed after feedback
}

export function ConceptFlow({ scenario, question, options, correctValue, feedback, concept }: ConceptFlowProps) {
  const [selected, setSelected] = useState<string | null>(null);
  const [revealed, setRevealed] = useState(false);

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: selected ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }}>🤔</span>
          <div style={{ flex: 1 }}>
            <div style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', lineHeight: 1.7, marginBottom: 'var(--space-md)' }}>
              <Markdown components={markdownComponents}>{scenario}</Markdown>
            </div>
            <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', fontWeight: 600, margin: '0 0 var(--space-lg)' }}>{question}</p>

            {!selected && (
              <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
                {options.map((option) => (
                  <button
                    key={option.value}
                    onClick={() => setSelected(option.value)}
                    style={{
                      background: 'var(--bg-elevated)',
                      color: 'var(--text-primary)',
                      border: '1px solid var(--bg-border)',
                      borderRadius: 'var(--radius-sm)',
                      padding: '8px 16px',
                      fontSize: '0.9375rem',
                      fontFamily: 'inherit',
                      cursor: 'pointer',
                    }}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {selected && (
        <div style={{ padding: 'var(--space-lg) var(--space-xl)', background: selected === correctValue ? 'rgba(90,158,106,0.05)' : 'rgba(196,107,58,0.05)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">{selected === correctValue ? '✓' : '→'}</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <Markdown components={markdownComponents}>{feedback[selected] ?? ''}</Markdown>
            </div>
          </div>

          {!revealed && (
            <button
              onClick={() => setRevealed(true)}
              style={{
                marginTop: 'var(--space-lg)',
                background: 'var(--signal)',
                color: 'var(--bg-void)',
                border: 'none',
                borderRadius: 'var(--radius-sm)',
                padding: '6px 14px',
                fontSize: '0.8125rem',
                fontFamily: 'var(--font-display)',
                fontWeight: 500,
                cursor: 'pointer',
              }}
            >
              Continue →
            </button>
          )}
        </div>
      )}

      {revealed && (
        <div style={{ padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">💡</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>The concept</p>
              <Markdown components={markdownComponents}>{concept}</Markdown>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/* ══════════════════════════════════════════════════════════════
   2. DiagnoseMechanism — diagnose root cause before it's named
   ══════════════════════════════════════════════════════════════ */
export interface DiagnoseMechanismProps {
  scenario: string; // markdown, may contain a fenced code block
  question: string;
  options: FlowOption[];
  correctValue: string;
  feedback: Record<string, string>;
  mechanism: string; // markdown, root-cause explanation revealed after
}

export function DiagnoseMechanism({ scenario, question, options, correctValue, feedback, mechanism }: DiagnoseMechanismProps) {
  const [selected, setSelected] = useState<string | null>(null);
  const [revealed, setRevealed] = useState(false);

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: selected ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }}>🔍</span>
          <div style={{ flex: 1 }}>
            <div style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', lineHeight: 1.7, marginBottom: 'var(--space-md)' }}>
              <Markdown components={markdownComponents}>{scenario}</Markdown>
            </div>
            <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', fontWeight: 600, margin: '0 0 var(--space-lg)' }}>{question}</p>

            {!selected && (
              <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
                {options.map((option) => (
                  <button
                    key={option.value}
                    onClick={() => setSelected(option.value)}
                    style={{
                      background: 'var(--bg-elevated)',
                      color: 'var(--text-primary)',
                      border: '1px solid var(--bg-border)',
                      borderRadius: 'var(--radius-sm)',
                      padding: '8px 16px',
                      fontSize: '0.9375rem',
                      fontFamily: 'inherit',
                      cursor: 'pointer',
                    }}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {selected && (
        <div style={{ padding: 'var(--space-lg) var(--space-xl)', background: selected === correctValue ? 'rgba(90,158,106,0.05)' : 'rgba(196,107,58,0.05)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">{selected === correctValue ? '✓' : '→'}</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <Markdown components={markdownComponents}>{feedback[selected] ?? ''}</Markdown>
            </div>
          </div>

          {!revealed && (
            <button
              onClick={() => setRevealed(true)}
              style={{
                marginTop: 'var(--space-lg)',
                background: 'var(--signal)',
                color: 'var(--bg-void)',
                border: 'none',
                borderRadius: 'var(--radius-sm)',
                padding: '6px 14px',
                fontSize: '0.8125rem',
                fontFamily: 'var(--font-display)',
                fontWeight: 500,
                cursor: 'pointer',
              }}
            >
              Continue →
            </button>
          )}
        </div>
      )}

      {revealed && (
        <div style={{ padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">💡</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Root cause</p>
              <Markdown components={markdownComponents}>{mechanism}</Markdown>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/* ══════════════════════════════════════════════════════════════
   3. SpotFlaw — find the flaw in real code before it's named
   ══════════════════════════════════════════════════════════════ */
export interface SpotFlawProps {
  code: string; // literal code, rendered in a <pre><code> block
  question: string;
  options: FlowOption[]; // candidate flaw descriptions/locations
  correctValue: string;
  feedback: Record<string, string>;
  flawExplanation: string; // markdown, revealed after
}

export function SpotFlaw({ code, question, options, correctValue, feedback, flawExplanation }: SpotFlawProps) {
  const [selected, setSelected] = useState<string | null>(null);
  const [revealed, setRevealed] = useState(false);

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: selected ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }}>🐛</span>
          <div style={{ flex: 1 }}>
            <p style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', fontWeight: 500, margin: '0 0 var(--space-md)' }}>{question}</p>

            <pre
              style={{
                fontFamily: 'var(--font-code)',
                background: 'var(--bg-elevated)',
                padding: 'var(--space-md)',
                borderRadius: 'var(--radius-sm)',
                overflowX: 'auto',
                fontSize: '0.8125rem',
                whiteSpace: 'pre',
                margin: '0 0 var(--space-lg)',
              }}
            >
              <code>{code}</code>
            </pre>

            {!selected && (
              <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
                {options.map((option) => (
                  <button
                    key={option.value}
                    onClick={() => setSelected(option.value)}
                    style={{
                      background: 'var(--bg-elevated)',
                      color: 'var(--text-primary)',
                      border: '1px solid var(--bg-border)',
                      borderRadius: 'var(--radius-sm)',
                      padding: '8px 16px',
                      fontSize: '0.9375rem',
                      fontFamily: 'inherit',
                      cursor: 'pointer',
                    }}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {selected && (
        <div style={{ padding: 'var(--space-lg) var(--space-xl)', background: selected === correctValue ? 'rgba(90,158,106,0.05)' : 'rgba(196,107,58,0.05)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">{selected === correctValue ? '✓' : '→'}</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <Markdown components={markdownComponents}>{feedback[selected] ?? ''}</Markdown>
            </div>
          </div>

          {!revealed && (
            <button
              onClick={() => setRevealed(true)}
              style={{
                marginTop: 'var(--space-lg)',
                background: 'var(--signal)',
                color: 'var(--bg-void)',
                border: 'none',
                borderRadius: 'var(--radius-sm)',
                padding: '6px 14px',
                fontSize: '0.8125rem',
                fontFamily: 'var(--font-display)',
                fontWeight: 500,
                cursor: 'pointer',
              }}
            >
              Continue →
            </button>
          )}
        </div>
      )}

      {revealed && (
        <div style={{ padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">💡</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>The flaw</p>
              <Markdown components={markdownComponents}>{flawExplanation}</Markdown>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/* ══════════════════════════════════════════════════════════════
   4. SequenceIt — order steps before the correct sequence is explained
   ══════════════════════════════════════════════════════════════ */
export interface SequenceItProps {
  question: string;
  steps: string[]; // given in CORRECT order
  explanation: string; // markdown, revealed after checking
}

function shuffleSteps<T>(arr: T[]): T[] {
  const result = [...arr];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

export function SequenceIt({ question, steps, explanation }: SequenceItProps) {
  // Shuffle once per `steps` identity, not on every render.
  const initialOrder = useMemo(() => shuffleSteps(steps), [steps]);
  const [order, setOrder] = useState<string[]>(initialOrder);
  const [checked, setChecked] = useState(false);

  const moveUp = (index: number) => {
    if (checked || index === 0) return;
    const next = [...order];
    [next[index - 1], next[index]] = [next[index], next[index - 1]];
    setOrder(next);
  };

  const moveDown = (index: number) => {
    if (checked || index === order.length - 1) return;
    const next = [...order];
    [next[index], next[index + 1]] = [next[index + 1], next[index]];
    setOrder(next);
  };

  const isCorrectPosition = (step: string, index: number) => steps[index] === step;

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: checked ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }}>🔢</span>
          <div style={{ flex: 1 }}>
            <p style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', fontWeight: 500, margin: '0 0 var(--space-lg)' }}>{question}</p>

            <ol style={{ listStyle: 'none', padding: 0, margin: '0 0 var(--space-lg)' }}>
              {order.map((step, index) => (
                <li key={step} style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-md)', padding: '6px 0' }}>
                  <span
                    style={{
                      background: checked ? (isCorrectPosition(step, index) ? 'rgba(90,158,106,0.12)' : 'rgba(196,107,58,0.12)') : 'var(--bg-elevated)',
                      color: checked ? (isCorrectPosition(step, index) ? 'var(--success)' : 'var(--rust)') : 'var(--text-primary)',
                      borderRadius: '50%',
                      width: 24,
                      height: 24,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontSize: '0.8125rem',
                      fontWeight: 600,
                      fontFamily: 'var(--font-display)',
                      flexShrink: 0,
                    }}
                  >
                    {checked ? (isCorrectPosition(step, index) ? '✓' : '✕') : index + 1}
                  </span>
                  <div style={{ flex: 1, color: 'var(--text-primary)', fontSize: '0.9375rem' }}>{step}</div>
                  {!checked && (
                    <div style={{ display: 'flex', gap: 4, flexShrink: 0 }}>
                      <button
                        onClick={() => moveUp(index)}
                        disabled={index === 0}
                        aria-label={`Move "${step}" up`}
                        style={{
                          background: 'var(--bg-elevated)',
                          color: index === 0 ? 'var(--text-tertiary)' : 'var(--text-primary)',
                          border: '1px solid var(--bg-border)',
                          borderRadius: 'var(--radius-sm)',
                          padding: '4px 8px',
                          fontSize: '0.75rem',
                          cursor: index === 0 ? 'not-allowed' : 'pointer',
                        }}
                      >
                        ↑
                      </button>
                      <button
                        onClick={() => moveDown(index)}
                        disabled={index === order.length - 1}
                        aria-label={`Move "${step}" down`}
                        style={{
                          background: 'var(--bg-elevated)',
                          color: index === order.length - 1 ? 'var(--text-tertiary)' : 'var(--text-primary)',
                          border: '1px solid var(--bg-border)',
                          borderRadius: 'var(--radius-sm)',
                          padding: '4px 8px',
                          fontSize: '0.75rem',
                          cursor: index === order.length - 1 ? 'not-allowed' : 'pointer',
                        }}
                      >
                        ↓
                      </button>
                    </div>
                  )}
                </li>
              ))}
            </ol>

            {!checked && (
              <button
                onClick={() => setChecked(true)}
                style={{
                  background: 'var(--gold)',
                  color: 'var(--bg-void)',
                  border: 'none',
                  borderRadius: 'var(--radius-sm)',
                  padding: '6px 14px',
                  fontSize: '0.8125rem',
                  fontFamily: 'var(--font-display)',
                  fontWeight: 500,
                  cursor: 'pointer',
                }}
              >
                Check my order
              </button>
            )}
          </div>
        </div>
      </div>

      {checked && (
        <div style={{ padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div aria-live="polite">
            <div style={{ display: 'flex', gap: 'var(--space-sm)', marginBottom: 'var(--space-lg)' }}>
              <button
                onClick={() => setChecked(false)}
                style={{
                  background: 'transparent',
                  color: 'var(--signal)',
                  border: '1px solid var(--signal)',
                  borderRadius: 'var(--radius-sm)',
                  padding: '6px 14px',
                  fontSize: '0.8125rem',
                  fontFamily: 'inherit',
                  fontWeight: 500,
                  cursor: 'pointer',
                }}
              >
                Try again
              </button>
            </div>

            <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              Correct order &amp; why
            </p>
            <ol style={{ listStyle: 'none', padding: 0, margin: '0 0 var(--space-md)' }}>
              {steps.map((step, index) => (
                <li key={step} style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-md)', padding: '4px 0' }}>
                  <span style={{ color: 'var(--text-tertiary)', fontSize: '0.75rem', fontFamily: 'var(--font-display)', flexShrink: 0, width: 16 }}>{index + 1}</span>
                  <div style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem' }}>{step}</div>
                </li>
              ))}
            </ol>
            <div style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <Markdown components={markdownComponents}>{explanation}</Markdown>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
