/* ─── Guess-first lesson content templates ───
 * Ported from the medinformics content-template taxonomy (concept-flow,
 * diagnose-mechanism, spot-flaw, sequence-it) and adapted to bedcoders'
 * Lesson.tsx content-section model. Draft implementation generated by the
 * local qwen3-coder-next:latest model (Ollama, localhost:11434) from a
 * spec prompt referencing the existing InteractiveGuess component for
 * style parity, then reviewed and corrected by hand for type-safety and
 * a state-management bug in SequenceIt (see below).
 *
 * Shared pedagogy: the learner commits to a choice/order BEFORE any
 * explanation is shown, gets feedback tied to their SPECIFIC choice
 * (not generic right/wrong text), and only then sees the underlying
 * concept/mechanism/flaw/correct-order revealed.
 *
 * Accessibility pass (spoonie-accessibility guidelines): every
 * interactive control meets the 48x48px minimum touch target; every
 * reveal moves keyboard/screen-reader focus onto the newly-shown panel
 * instead of losing it to nowhere (WCAG 2.4.3); every template offers a
 * no-penalty "Try again" once the answer is revealed, so a wrong guess
 * is never a dead end that forces a page reload — and "Try again" itself
 * returns focus to the question block rather than dropping it on
 * document.body; and correctness is always stated in real text, never
 * left to a colour wash plus an aria-hidden glyph (WCAG 1.4.1).
 */
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import Markdown from 'react-markdown';
import { markdownComponents } from './markdownComponents';

/* ─── Shared a11y helpers ─── */

// 48x48px is the spoonie-accessibility minimum touch target — motor
// control (tremor, joint pain, one-handed phone use) makes anything
// smaller a real barrier, not a cosmetic nitpick.
const MIN_TOUCH = 48;

/** Moves focus onto a newly-revealed panel the moment it appears, so a
 * keyboard or screen-reader user isn't stranded at a control that just
 * disappeared from the DOM. The target must have tabIndex={-1}. */
function useRevealFocus<T extends HTMLElement>(active: boolean) {
  const ref = useRef<T | null>(null);
  useEffect(() => {
    if (active) ref.current?.focus();
  }, [active]);
  return ref;
}

/** Mirror image of useRevealFocus, for the "Try again" path. reset()
 * unmounts the panel that holds the Try Again button, so without this the
 * browser drops focus onto document.body — which strands a keyboard or
 * screen-reader user back at the top of the page and makes the control
 * built so a wrong answer isn't a dead end into a dead end itself.
 *
 * Pass the expression that is true exactly when the widget is in its
 * pristine, pre-answer state. Focus is moved only on a RE-entry into that
 * state (never on first mount), so the target must have tabIndex={-1}. */
function useReturnFocus<T extends HTMLElement>(atInitialState: boolean) {
  const ref = useRef<T | null>(null);
  const hasLeftInitialState = useRef(false);
  useEffect(() => {
    if (!atInitialState) {
      hasLeftInitialState.current = true;
      return;
    }
    if (hasLeftInitialState.current) {
      hasLeftInitialState.current = false;
      ref.current?.focus();
    }
  }, [atInitialState]);
  return ref;
}

/** Focus target for the question/prompt block a "Try again" returns to.
 * tabIndex={-1} keeps it out of the Tab order; the outline is suppressed
 * because it is only ever reached programmatically. */
const questionBlockFocusStyle: React.CSSProperties = { flex: 1, outline: 'none' };

/** Visually hidden but present for assistive tech — real text in the DOM,
 * which aria-label alone would not give (and which braille displays and
 * "read from here" navigation need). Mirrors globals.css .sr-only. */
const visuallyHidden: React.CSSProperties = {
  position: 'absolute',
  width: 1,
  height: 1,
  padding: 0,
  margin: -1,
  overflow: 'hidden',
  clip: 'rect(0,0,0,0)',
  whiteSpace: 'nowrap',
  border: 0,
};

/* Deliberately gentle wording. The product never says "Wrong" or
 * "Incorrect" to a learner, and the not-quite glyph is a grey arrow rather
 * than a red cross on purpose — keep it that way. */
const VERDICT_CORRECT = 'Correct';
const VERDICT_NOT_QUITE = 'Not quite';

/** The verdict as real, visible, screen-reader-available text.
 * WCAG 1.4.1 (Use of Colour, Level A): before this existed, whether the
 * learner got it right was carried only by the panel's green-vs-rust wash
 * and an aria-hidden ✓/→ glyph, so a screen-reader user got no indication
 * at all. Rendered BEFORE the feedback prose so it is heard first. */
function Verdict({ correct }: { correct: boolean }) {
  return (
    <p
      style={{
        margin: '0 0 var(--space-xs)',
        fontWeight: 600,
        fontFamily: 'var(--font-display)',
        fontSize: '0.6875rem',
        textTransform: 'uppercase',
        letterSpacing: '0.06em',
        color: correct ? 'var(--success)' : 'var(--text-tertiary)',
      }}
    >
      {correct ? VERDICT_CORRECT : VERDICT_NOT_QUITE}
    </p>
  );
}

const optionButtonStyle: React.CSSProperties = {
  background: 'var(--bg-elevated)',
  color: 'var(--text-primary)',
  border: '1px solid var(--bg-border)',
  borderRadius: 'var(--radius-sm)',
  padding: '12px 20px',
  minHeight: MIN_TOUCH,
  fontSize: '0.9375rem',
  fontFamily: 'inherit',
  cursor: 'pointer',
};

const primaryActionButtonStyle: React.CSSProperties = {
  background: 'var(--signal)',
  color: 'var(--bg-void)',
  border: 'none',
  borderRadius: 'var(--radius-sm)',
  padding: '12px 22px',
  minHeight: MIN_TOUCH,
  fontSize: '0.875rem',
  fontFamily: 'var(--font-display)',
  fontWeight: 500,
  cursor: 'pointer',
};

const secondaryActionButtonStyle: React.CSSProperties = {
  background: 'transparent',
  color: 'var(--signal)',
  border: '1px solid var(--signal)',
  borderRadius: 'var(--radius-sm)',
  padding: '12px 22px',
  minHeight: MIN_TOUCH,
  fontSize: '0.875rem',
  fontFamily: 'inherit',
  fontWeight: 500,
  cursor: 'pointer',
};

/** Focusable wrapper for a revealed panel — tabIndex={-1} keeps it out of
 * normal Tab order (it's not a control) while still being a valid
 * programmatic focus target. outline is suppressed since this is never
 * reached by Tab, only by useRevealFocus. */
const revealPanelFocusStyle: React.CSSProperties = { outline: 'none' };

/** Consistent, low-pressure "start over" control — every template that can
 * end in a "wrong" state offers this once the answer is revealed, so
 * getting it wrong is never a dead end. */
function TryAgainButton({ onClick, label = 'Try again ↺' }: { onClick: () => void; label?: string }) {
  return (
    <button onClick={onClick} style={{ ...secondaryActionButtonStyle, marginBottom: 'var(--space-lg)' }}>
      {label}
    </button>
  );
}

/* ─── Shared option type ─── */
export interface FlowOption {
  label: string;
  value: string;
}

/* ══════════════════════════════════════════════════════════════
   1. ConceptFlow — classify a real example before the concept is named
   ══════════════════════════════════════════════════════════════ */
export interface ConceptFlowProps {
  scenario: string; // markdown; the real example presented first
  question: string; // plain text; what to classify
  options: FlowOption[];
  correctValue: string;
  feedback: Record<string, string>; // markdown, keyed by option value
  concept: string; // markdown; general concept, revealed after feedback
}

export function ConceptFlow({ scenario, question, options, correctValue, feedback, concept }: ConceptFlowProps) {
  const [selected, setSelected] = useState<string | null>(null);
  const [revealed, setRevealed] = useState(false);
  const feedbackRef = useRevealFocus<HTMLDivElement>(selected !== null);
  const conceptRef = useRevealFocus<HTMLDivElement>(revealed);
  const questionRef = useReturnFocus<HTMLDivElement>(selected === null);

  function reset() {
    setSelected(null);
    setRevealed(false);
  }

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: selected ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">🤔</span>
          <div ref={questionRef} tabIndex={-1} style={questionBlockFocusStyle}>
            <div style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', lineHeight: 1.7, marginBottom: 'var(--space-md)' }}>
              <Markdown components={markdownComponents}>{scenario}</Markdown>
            </div>
            <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', fontWeight: 600, margin: '0 0 var(--space-lg)' }}>{question}</p>

            {!selected && (
              <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
                {options.map((option) => (
                  <button key={option.value} onClick={() => setSelected(option.value)} style={optionButtonStyle}>
                    {option.label}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {selected && (
        <div
          ref={feedbackRef}
          tabIndex={-1}
          style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: selected === correctValue ? 'rgba(90,158,106,0.05)' : 'rgba(196,107,58,0.05)' }}
        >
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">{selected === correctValue ? '✓' : '→'}</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <Verdict correct={selected === correctValue} />
              <Markdown components={markdownComponents}>{feedback[selected] ?? ''}</Markdown>
            </div>
          </div>

          {!revealed && (
            <button onClick={() => setRevealed(true)} style={{ ...primaryActionButtonStyle, marginTop: 'var(--space-lg)' }}>
              Continue →
            </button>
          )}
        </div>
      )}

      {revealed && (
        <div ref={conceptRef} tabIndex={-1} style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">💡</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>The concept</p>
              <Markdown components={markdownComponents}>{concept}</Markdown>
            </div>
          </div>
          <div style={{ marginTop: 'var(--space-lg)' }}>
            <TryAgainButton onClick={reset} />
          </div>
        </div>
      )}
    </div>
  );
}

/* ══════════════════════════════════════════════════════════════
   2. DiagnoseMechanism — diagnose root cause before it's named
   ══════════════════════════════════════════════════════════════ */
export interface DiagnoseMechanismProps {
  scenario: string; // markdown, may contain a fenced code block
  question: string;
  options: FlowOption[];
  correctValue: string;
  feedback: Record<string, string>;
  mechanism: string; // markdown, root-cause explanation revealed after
}

export function DiagnoseMechanism({ scenario, question, options, correctValue, feedback, mechanism }: DiagnoseMechanismProps) {
  const [selected, setSelected] = useState<string | null>(null);
  const [revealed, setRevealed] = useState(false);
  const feedbackRef = useRevealFocus<HTMLDivElement>(selected !== null);
  const mechanismRef = useRevealFocus<HTMLDivElement>(revealed);
  const questionRef = useReturnFocus<HTMLDivElement>(selected === null);

  function reset() {
    setSelected(null);
    setRevealed(false);
  }

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: selected ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">🔍</span>
          <div ref={questionRef} tabIndex={-1} style={questionBlockFocusStyle}>
            <div style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', lineHeight: 1.7, marginBottom: 'var(--space-md)' }}>
              <Markdown components={markdownComponents}>{scenario}</Markdown>
            </div>
            <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', fontWeight: 600, margin: '0 0 var(--space-lg)' }}>{question}</p>

            {!selected && (
              <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
                {options.map((option) => (
                  <button key={option.value} onClick={() => setSelected(option.value)} style={optionButtonStyle}>
                    {option.label}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {selected && (
        <div
          ref={feedbackRef}
          tabIndex={-1}
          style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: selected === correctValue ? 'rgba(90,158,106,0.05)' : 'rgba(196,107,58,0.05)' }}
        >
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">{selected === correctValue ? '✓' : '→'}</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <Verdict correct={selected === correctValue} />
              <Markdown components={markdownComponents}>{feedback[selected] ?? ''}</Markdown>
            </div>
          </div>

          {!revealed && (
            <button onClick={() => setRevealed(true)} style={{ ...primaryActionButtonStyle, marginTop: 'var(--space-lg)' }}>
              Continue →
            </button>
          )}
        </div>
      )}

      {revealed && (
        <div ref={mechanismRef} tabIndex={-1} style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">💡</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Root cause</p>
              <Markdown components={markdownComponents}>{mechanism}</Markdown>
            </div>
          </div>
          <div style={{ marginTop: 'var(--space-lg)' }}>
            <TryAgainButton onClick={reset} />
          </div>
        </div>
      )}
    </div>
  );
}

/* ══════════════════════════════════════════════════════════════
   3. SpotFlaw — find the flaw in real code before it's named
   ══════════════════════════════════════════════════════════════ */
export interface SpotFlawProps {
  code: string; // literal code, rendered in a <pre><code> block
  question: string;
  options: FlowOption[]; // candidate flaw descriptions/locations
  correctValue: string;
  feedback: Record<string, string>;
  flawExplanation: string; // markdown, revealed after
}

export function SpotFlaw({ code, question, options, correctValue, feedback, flawExplanation }: SpotFlawProps) {
  const [selected, setSelected] = useState<string | null>(null);
  const [revealed, setRevealed] = useState(false);
  const feedbackRef = useRevealFocus<HTMLDivElement>(selected !== null);
  const flawRef = useRevealFocus<HTMLDivElement>(revealed);
  const questionRef = useReturnFocus<HTMLDivElement>(selected === null);

  function reset() {
    setSelected(null);
    setRevealed(false);
  }

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: selected ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">🐛</span>
          <div ref={questionRef} tabIndex={-1} style={questionBlockFocusStyle}>
            <p style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', fontWeight: 500, margin: '0 0 var(--space-md)' }}>{question}</p>

            <pre
              tabIndex={0}
              role="group"
              aria-label="Code to review"
              style={{
                fontFamily: 'var(--font-code)',
                background: 'var(--bg-elevated)',
                padding: 'var(--space-md)',
                borderRadius: 'var(--radius-sm)',
                overflowX: 'auto',
                fontSize: '0.8125rem',
                whiteSpace: 'pre',
                margin: '0 0 var(--space-lg)',
              }}
            >
              <code>{code}</code>
            </pre>

            {!selected && (
              <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
                {options.map((option) => (
                  <button key={option.value} onClick={() => setSelected(option.value)} style={optionButtonStyle}>
                    {option.label}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {selected && (
        <div
          ref={feedbackRef}
          tabIndex={-1}
          style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: selected === correctValue ? 'rgba(90,158,106,0.05)' : 'rgba(196,107,58,0.05)' }}
        >
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">{selected === correctValue ? '✓' : '→'}</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <Verdict correct={selected === correctValue} />
              <Markdown components={markdownComponents}>{feedback[selected] ?? ''}</Markdown>
            </div>
          </div>

          {!revealed && (
            <button onClick={() => setRevealed(true)} style={{ ...primaryActionButtonStyle, marginTop: 'var(--space-lg)' }}>
              Continue →
            </button>
          )}
        </div>
      )}

      {revealed && (
        <div ref={flawRef} tabIndex={-1} style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">💡</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>The flaw</p>
              <Markdown components={markdownComponents}>{flawExplanation}</Markdown>
            </div>
          </div>
          <div style={{ marginTop: 'var(--space-lg)' }}>
            <TryAgainButton onClick={reset} />
          </div>
        </div>
      )}
    </div>
  );
}

/* ══════════════════════════════════════════════════════════════
   4. SequenceIt — order steps before the correct sequence is explained
   ══════════════════════════════════════════════════════════════ */
export interface SequenceItProps {
  question: string;
  steps: string[]; // given in CORRECT order
  explanation: string; // markdown, revealed after checking
}

function shuffleSteps<T>(arr: T[]): T[] {
  const result = [...arr];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

export function SequenceIt({ question, steps, explanation }: SequenceItProps) {
  // Shuffle once per `steps` identity, not on every render.
  const initialOrder = useMemo(() => shuffleSteps(steps), [steps]);
  const [order, setOrder] = useState<string[]>(initialOrder);
  const [checked, setChecked] = useState(false);
  // Reordering is otherwise silent: the buttons rearrange the DOM but say
  // nothing, so a screen-reader user cannot tell a successful move from a
  // no-op. This polite region narrates every move.
  const [moveAnnouncement, setMoveAnnouncement] = useState('');
  const resultsRef = useRevealFocus<HTMLDivElement>(checked);
  const questionRef = useReturnFocus<HTMLDivElement>(!checked);

  const moveUp = (index: number) => {
    if (checked || index === 0) return;
    const step = order[index];
    const next = [...order];
    [next[index - 1], next[index]] = [next[index], next[index - 1]];
    setOrder(next);
    setMoveAnnouncement(`Moved ${step} to position ${index} of ${next.length}`);
  };

  const moveDown = (index: number) => {
    if (checked || index === order.length - 1) return;
    const step = order[index];
    const next = [...order];
    [next[index], next[index + 1]] = [next[index + 1], next[index]];
    setOrder(next);
    setMoveAnnouncement(`Moved ${step} to position ${index + 2} of ${next.length}`);
  };

  function reset() {
    setChecked(false);
    setMoveAnnouncement('');
  }

  const isCorrectPosition = (step: string, index: number) => steps[index] === step;

  const iconButtonStyle: React.CSSProperties = {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--bg-border)',
    borderRadius: 'var(--radius-sm)',
    minWidth: MIN_TOUCH,
    minHeight: MIN_TOUCH,
    fontSize: '0.9375rem',
    cursor: 'pointer',
  };

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: checked ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">🔢</span>
          <div ref={questionRef} tabIndex={-1} style={questionBlockFocusStyle}>
            <p style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', fontWeight: 500, margin: '0 0 var(--space-lg)' }}>{question}</p>

            {/* Move narration. Off-screen but present in the DOM, and polite
              * so it never interrupts whatever is currently being read. */}
            <div role="status" aria-live="polite" style={visuallyHidden}>{moveAnnouncement}</div>

            <ol style={{ listStyle: 'none', padding: 0, margin: '0 0 var(--space-lg)' }}>
              {order.map((step, index) => (
                <li key={step} style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-md)', padding: '6px 0' }}>
                  {/* The visible position badge is aria-hidden (it swaps to a
                    * ✓/✕ glyph after checking), so the ordinal has to be
                    * carried in text of its own — without it the whole
                    * widget is unusable by ear. */}
                  <span style={visuallyHidden}>{`Position ${index + 1} of ${order.length}: `}</span>
                  <span
                    aria-hidden="true"
                    style={{
                      background: checked ? (isCorrectPosition(step, index) ? 'rgba(90,158,106,0.12)' : 'rgba(196,107,58,0.12)') : 'var(--bg-elevated)',
                      color: checked ? (isCorrectPosition(step, index) ? 'var(--success)' : 'var(--rust)') : 'var(--text-primary)',
                      borderRadius: '50%',
                      width: 24,
                      height: 24,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontSize: '0.8125rem',
                      fontWeight: 600,
                      fontFamily: 'var(--font-display)',
                      flexShrink: 0,
                    }}
                  >
                    {checked ? (isCorrectPosition(step, index) ? '✓' : '✕') : index + 1}
                  </span>
                  <div style={{ flex: 1, color: 'var(--text-primary)', fontSize: '0.9375rem' }}>
                    {step}
                    {checked && (
                      <span style={{ marginLeft: 8, fontSize: '0.75rem', color: isCorrectPosition(step, index) ? 'var(--success)' : 'var(--rust)', fontFamily: 'var(--font-display)' }}>
                        {isCorrectPosition(step, index) ? '(correct spot)' : '(out of order)'}
                      </span>
                    )}
                  </div>
                  {!checked && (
                    <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}>
                      <button onClick={() => moveUp(index)} disabled={index === 0} aria-label={`Move "${step}" up`} style={{ ...iconButtonStyle, color: index === 0 ? 'var(--text-tertiary)' : 'var(--text-primary)', cursor: index === 0 ? 'not-allowed' : 'pointer' }}>
                        ↑
                      </button>
                      <button onClick={() => moveDown(index)} disabled={index === order.length - 1} aria-label={`Move "${step}" down`} style={{ ...iconButtonStyle, color: index === order.length - 1 ? 'var(--text-tertiary)' : 'var(--text-primary)', cursor: index === order.length - 1 ? 'not-allowed' : 'pointer' }}>
                        ↓
                      </button>
                    </div>
                  )}
                </li>
              ))}
            </ol>

            {!checked && (
              <button onClick={() => setChecked(true)} style={primaryActionButtonStyle}>
                Check my order
              </button>
            )}
          </div>
        </div>
      </div>

      {checked && (
        <div ref={resultsRef} tabIndex={-1} style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div aria-live="polite">
            <div style={{ display: 'flex', gap: 'var(--space-sm)', marginBottom: 'var(--space-lg)' }}>
              <TryAgainButton onClick={reset} />
            </div>

            <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              Correct order &amp; why
            </p>
            <ol style={{ listStyle: 'none', padding: 0, margin: '0 0 var(--space-md)' }}>
              {steps.map((step, index) => (
                <li key={step} style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-md)', padding: '4px 0' }}>
                  <span style={{ color: 'var(--text-tertiary)', fontSize: '0.75rem', fontFamily: 'var(--font-display)', flexShrink: 0, width: 16 }}>{index + 1}</span>
                  <div style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem' }}>{step}</div>
                </li>
              ))}
            </ol>
            <div style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <Markdown components={markdownComponents}>{explanation}</Markdown>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}


/* ══════════════════════════════════════════════════════════════
   5. BuildIt — construct a JS object field-by-field with live preview
   ══════════════════════════════════════════════════════════════ */
export interface BuildField {
  key: string;
  prompt: string;
  options: FlowOption[];
  correctValue: string;
  feedback: Record<string, string>;
}

export interface BuildItProps {
  intro: string; // markdown
  objectName: string;
  fields: BuildField[];
  synthesis: string; // markdown
}

export function BuildIt({ intro, objectName, fields, synthesis }: BuildItProps) {
  const [fieldIndex, setFieldIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [feedbackGiven, setFeedbackGiven] = useState(false);

  const handleSelect = (value: string) => {
    setAnswers(prev => ({ ...prev, [fields[fieldIndex].key]: value }));
    setFeedbackGiven(true);
  };

  const continueToNext = () => {
    if (fieldIndex < fields.length - 1) {
      setFieldIndex(prev => prev + 1);
      setFeedbackGiven(false);
    }
  };

  function reset() {
    setFieldIndex(0);
    setAnswers({});
    setFeedbackGiven(false);
  }

  const isLastField = fieldIndex === fields.length - 1;

  // Show synthesis panel only when all fields have been answered
  const allAnswered = Object.keys(answers).length === fields.length;

  /* Answering an option unmounts the option buttons, so without a focus
   * target here focus fell to document.body on EVERY selection — 25-35 Tab
   * presses back to where the learner was. Note the hook ORDER: answering
   * the final field reveals the feedback panel and the synthesis panel in
   * the same commit, and React runs effects in declaration order, so the
   * feedback hook is declared last and wins. That is deliberate — the
   * feedback panel sits earlier in the DOM, so the learner reads their
   * feedback and reaches the synthesis by reading forward, instead of
   * having the last field's feedback skipped over. */
  const synthesisRef = useRevealFocus<HTMLDivElement>(allAnswered);
  const fieldFeedbackRef = useRevealFocus<HTMLDivElement>(feedbackGiven);
  const promptRef = useReturnFocus<HTMLDivElement>(fieldIndex === 0 && !feedbackGiven);

  // Build the live preview object string (showing only answered fields in order)
  const buildObjectString = () => {
    const answeredFields = fields.filter((field) => answers[field.key] !== undefined);
    const lines = answeredFields.map((field) => {
      const escapedValue = String(answers[field.key]).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
      return `  ${field.key}: "${escapedValue}"`;
    });
    if (lines.length === 0) return `const ${objectName} = {};`;
    return `const ${objectName} = {\n${lines.join(',\n')}\n};`;
  };

  const currentField = fields[fieldIndex];

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      {/* Intro Panel */}
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">🧱</span>
          <div ref={promptRef} tabIndex={-1} style={questionBlockFocusStyle}>
            <div style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', lineHeight: 1.7, marginBottom: 'var(--space-md)' }}>
              <Markdown components={markdownComponents}>{intro}</Markdown>
            </div>

            {/* Live Preview Code Block */}
            <pre
              aria-live="polite"
              aria-label="Live preview of the object you're building"
              style={{
                fontFamily: 'var(--font-code)',
                background: 'var(--bg-elevated)',
                padding: 'var(--space-md)',
                borderRadius: 'var(--radius-sm)',
                overflowX: 'auto',
                fontSize: '0.75rem',
                whiteSpace: 'pre',
                margin: '0 0 var(--space-lg)',
              }}
            >
              <code>{buildObjectString()}</code>
            </pre>

            {/* Field Construction Area */}
            <div style={{ marginTop: 'var(--space-md)' }}>
              {fieldIndex < fields.length && (
                <div>
                  <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', fontWeight: 600, margin: '0 0 var(--space-lg)' }}>
                    Field {fieldIndex + 1} of {fields.length}: {currentField.prompt}
                  </p>

                  {!feedbackGiven && (
                    <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
                      {currentField.options.map((option) => (
                        <button key={option.value} onClick={() => handleSelect(option.value)} style={optionButtonStyle}>
                          {option.label}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Feedback Panel */}
            {feedbackGiven && (
              <div
                ref={fieldFeedbackRef}
                tabIndex={-1}
                aria-live="polite"
                style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', marginTop: 'var(--space-lg)', background: answers[currentField.key] === currentField.correctValue ? 'rgba(90,158,106,0.05)' : 'rgba(196,107,58,0.05)' }}
              >
                <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
                  <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">{answers[currentField.key] === currentField.correctValue ? '✓' : '→'}</span>
                  <div style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
                    <Verdict correct={answers[currentField.key] === currentField.correctValue} />
                    <Markdown components={markdownComponents}>{currentField.feedback[answers[currentField.key]] ?? ''}</Markdown>
                  </div>
                </div>

                {!isLastField && (
                  <button onClick={continueToNext} style={{ ...primaryActionButtonStyle, marginTop: 'var(--space-lg)' }}>
                    Next field →
                  </button>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Synthesis Panel - shown only when all fields are answered */}
      {allAnswered && (
        <div ref={synthesisRef} tabIndex={-1} style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">✨</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>The complete object</p>

              <pre
                style={{
                  fontFamily: 'var(--font-code)',
                  background: 'rgba(0,0,0,0.03)',
                  padding: 'var(--space-md)',
                  borderRadius: 'var(--radius-sm)',
                  overflowX: 'auto',
                  fontSize: '0.75rem',
                  whiteSpace: 'pre',
                  margin: '0 0 var(--space-lg)',
                }}
              >
                <code>{buildObjectString()}</code>
              </pre>

              <Markdown components={markdownComponents}>{synthesis}</Markdown>
            </div>
          </div>
          <div style={{ marginTop: 'var(--space-lg)' }}>
            <TryAgainButton onClick={reset} />
          </div>
        </div>
      )}
    </div>
  );
}


/* ══════════════════════════════════════════════════════════════
   6. EvidenceStack — select all applicable evidence before it's explained
   ══════════════════════════════════════════════════════════════ */
export interface EvidenceItem {
  value: string;
  label: string;
  applicable: boolean;
}

export interface EvidenceStackProps {
  scenario: string; // markdown
  question: string;
  items: EvidenceItem[];
  explanation: Record<string, string>;
  synthesis: string; // markdown
}

export function EvidenceStack({ scenario, question, items, explanation, synthesis }: EvidenceStackProps) {
  const [selectedValues, setSelectedValues] = useState<Set<string>>(new Set());
  const [submitted, setSubmitted] = useState(false);
  const resultsRef = useRevealFocus<HTMLUListElement>(submitted);
  const questionRef = useReturnFocus<HTMLDivElement>(!submitted);

  const toggleSelection = (value: string) => {
    if (submitted) return;

    const next = new Set(selectedValues);
    if (next.has(value)) {
      next.delete(value);
    } else {
      next.add(value);
    }
    setSelectedValues(next);
  };

  const handleSubmit = () => {
    setSubmitted(true);
  };

  function reset() {
    setSelectedValues(new Set());
    setSubmitted(false);
  }

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: submitted ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">⚖️</span>
          <div ref={questionRef} tabIndex={-1} style={questionBlockFocusStyle}>
            <div style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', lineHeight: 1.7, marginBottom: 'var(--space-md)' }}>
              <Markdown components={markdownComponents}>{scenario}</Markdown>
            </div>
            <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', fontWeight: 600, margin: '0 0 var(--space-lg)' }}>{question}</p>

            {!submitted && (
              <div role="group" aria-label={question} style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
                {items.map((item) => {
                  const isSelected = selectedValues.has(item.value);
                  return (
                    <div
                      key={item.value}
                      role="checkbox"
                      aria-checked={isSelected}
                      aria-label={item.label}
                      tabIndex={0}
                      onClick={() => toggleSelection(item.value)}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' || e.key === ' ') {
                          e.preventDefault();
                          toggleSelection(item.value);
                        }
                      }}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '8px',
                        background: isSelected ? 'var(--signal)' : 'var(--bg-elevated)',
                        color: isSelected ? 'var(--bg-void)' : 'var(--text-primary)',
                        border: `1px solid ${isSelected ? 'transparent' : 'var(--bg-border)'}`,
                        borderRadius: 'var(--radius-sm)',
                        padding: '12px 20px',
                        minHeight: MIN_TOUCH,
                        fontSize: '0.9375rem',
                        fontFamily: 'inherit',
                        cursor: 'pointer',
                      }}
                    >
                      <span
                        aria-hidden="true"
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          width: 20,
                          height: 20,
                          borderRadius: 'var(--radius-sm)',
                          /* Was `background: 'currentColor'` with `color:
                           * var(--bg-void)` — currentColor resolved to that
                           * same colour, so the ✓ was painted in the box's
                           * own background and never appeared. The selected
                           * chip is var(--signal) on var(--bg-void) text, so
                           * invert that pairing here for a visible tick. */
                          background: isSelected ? 'var(--bg-void)' : 'var(--bg-elevated)',
                          color: isSelected ? 'var(--signal)' : 'var(--text-primary)',
                          fontSize: '0.875rem',
                          flexShrink: 0,
                        }}
                      >
                        {isSelected ? '✓' : ''}
                      </span>
                      <span>{item.label}</span>
                    </div>
                  );
                })}
              </div>
            )}

            {/* Submitted checkboxes (visualized with icons and color-coding) */}
            {submitted && (
              <ul ref={resultsRef} tabIndex={-1} aria-live="polite" style={{ ...revealPanelFocusStyle, listStyle: 'none', padding: 0, margin: '0 0 var(--space-lg)' }}>
                {items.map((item) => {
                  const isSelected = selectedValues.has(item.value);
                  const isApplicable = item.applicable;

                  let stateClass = '';
                  let icon = '';
                  let containerStyle: React.CSSProperties = {};

                  if (isSelected && isApplicable) {
                    // Correctly selected
                    stateClass = 'correct';
                    icon = '✓';
                    containerStyle = { background: 'rgba(90,158,106,0.05)' };
                  } else if (isSelected && !isApplicable) {
                    // Wrong / false positive
                    stateClass = 'incorrect';
                    icon = '✕';
                    containerStyle = { background: 'rgba(196,107,58,0.05)' };
                  } else if (!isSelected && isApplicable) {
                    // Missed
                    stateClass = 'missed';
                    icon = '!';
                    containerStyle = { background: 'rgba(196,107,58,0.05)' };
                  } else {
                    // Correctly excluded - neutral styling (muted)
                    stateClass = 'excluded';
                    icon = '';
                    containerStyle = { background: 'var(--bg-elevated)', opacity: 0.9 };
                  }

                  return (
                    <li key={item.value} style={{ ...containerStyle, borderRadius: 'var(--radius-sm)', padding: '12px', margin: '0 0 var(--space-xs)' }}>
                      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 'var(--space-md)' }}>
                        <span
                          aria-hidden="true"
                          style={{
                            fontSize: '1.125rem',
                            flexShrink: 0,
                            color: stateClass === 'correct' ? 'var(--success)' : (stateClass === 'missed' || stateClass === 'incorrect' ? 'var(--rust)' : 'var(--text-tertiary)'),
                          }}
                        >
                          {icon}
                        </span>
                        <div style={{ flex: 1 }}>
                          <p
                            style={{
                              margin: '0 0 var(--space-xs)',
                              fontWeight: 600,
                              color: stateClass === 'excluded' ? 'var(--text-tertiary)' : 'var(--text-primary)',
                            }}
                          >
                            {item.label}
                          </p>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <span
                              style={{
                                fontSize: '0.75rem',
                                padding: '2px 6px',
                                borderRadius: 'var(--radius-sm)',
                                background: stateClass === 'excluded' ? 'rgba(128,128,128,0.1)' : (stateClass === 'incorrect' || stateClass === 'missed' ? 'rgba(196,107,58,0.1)' : 'rgba(90,158,106,0.1)'),
                                color: stateClass === 'excluded' ? 'var(--text-tertiary)' : (stateClass === 'incorrect' || stateClass === 'missed' ? 'var(--rust)' : 'var(--success)'),
                                fontFamily: 'var(--font-display)',
                              }}
                            >
                              {stateClass.toUpperCase()}
                            </span>
                          </div>
                        </div>
                      </div>

                      {/* Explanation */}
                      <div style={{ margin: 'var(--space-md) 0 0', fontSize: '0.9375rem', lineHeight: 1.7 }}>
                        <Markdown components={markdownComponents}>{explanation[item.value] ?? ''}</Markdown>
                      </div>
                    </li>
                  );
                })}
              </ul>
            )}
          </div>
        </div>

        {/* Submit button */}
        {!submitted && (
          <div style={{ marginTop: 'var(--space-md)' }}>
            <button onClick={handleSubmit} style={primaryActionButtonStyle}>
              Check my answers
            </button>
          </div>
        )}
      </div>

      {/* Synthesis Panel */}
      {submitted && (
        <div style={{ padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
            <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              Why it matters
            </p>
            <Markdown components={markdownComponents}>{synthesis}</Markdown>
          </div>
          <div style={{ marginTop: 'var(--space-lg)' }}>
            <TryAgainButton onClick={reset} />
          </div>
        </div>
      )}
    </div>
  );
}


/* ══════════════════════════════════════════════════════════════
   7. PredictNumber — free-recall numeric prediction (unggraded)
   ══════════════════════════════════════════════════════════════ */
export interface PredictNumberProps {
  scenario: string; // markdown, may contain a fenced code block
  question: string;
  unit?: string;
  actualValue: string;
  explanation: string; // markdown, revealed after
}

export function PredictNumber({ scenario, question, unit, actualValue, explanation }: PredictNumberProps) {
  const [prediction, setPrediction] = useState<string>('');
  const [revealed, setRevealed] = useState(false);
  const resultsRef = useRevealFocus<HTMLDivElement>(revealed);
  const questionRef = useReturnFocus<HTMLDivElement>(!revealed);
  // A hardcoded id collides the moment a lesson uses two of these — duplicate
  // ids, and the second label points at the first input.
  const inputId = useId();

  function reset() {
    setPrediction('');
    setRevealed(false);
  }

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)', borderBottom: revealed ? '1px solid var(--bg-border)' : 'none' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">🎯</span>
          <div ref={questionRef} tabIndex={-1} style={questionBlockFocusStyle}>
            <div style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', lineHeight: 1.7, marginBottom: 'var(--space-md)' }}>
              <Markdown components={markdownComponents}>{scenario}</Markdown>
            </div>
            <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', fontWeight: 600, margin: '0 0 var(--space-lg)' }}>{question}</p>

            {!revealed && (
              <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'center', flexWrap: 'wrap' }}>
                <label htmlFor={inputId} style={visuallyHidden}>
                  Enter your numeric prediction
                </label>
                <input
                  id={inputId}
                  type="text"
                  inputMode="decimal"
                  value={prediction}
                  onChange={(e) => setPrediction(e.target.value)}
                  placeholder={unit ? `e.g. 42 ${unit}` : 'e.g. 42'}
                  style={{
                    background: 'var(--bg-elevated)',
                    color: 'var(--text-primary)',
                    border: '1px solid var(--bg-border)',
                    borderRadius: 'var(--radius-sm)',
                    padding: '10px 12px',
                    minHeight: MIN_TOUCH,
                    fontSize: '0.9375rem',
                    fontFamily: 'inherit',
                    width: unit ? 'auto' : '200px',
                    maxWidth: '240px',
                    flexShrink: 0,
                    boxSizing: 'border-box',
                  }}
                />
                {unit && (
                  <span style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', fontFamily: 'inherit' }}>{unit}</span>
                )}
                <button onClick={() => setRevealed(true)} disabled={!prediction.trim()} style={{ ...primaryActionButtonStyle, background: !prediction.trim() ? 'var(--bg-border)' : 'var(--gold)', color: !prediction.trim() ? 'var(--text-tertiary)' : 'var(--bg-void)', cursor: !prediction.trim() ? 'not-allowed' : 'pointer' }}>
                  Reveal answer
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {revealed && (
        <div ref={resultsRef} tabIndex={-1} style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
            <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Your prediction &amp; the reality</p>

            <div style={{ display: 'flex', gap: 'var(--space-md)', marginBottom: 'var(--space-lg)' }}>
              <span aria-hidden="true" style={{ color: 'var(--text-tertiary)', fontSize: '0.75rem', fontFamily: 'var(--font-display)', flexShrink: 0, width: 16 }}>🔍</span>
              <div>
                <p style={{ margin: '0 0 var(--space-xs)', color: 'var(--text-secondary)', fontSize: '0.9375rem' }}>
                  Your prediction:
                  <strong style={{ color: 'var(--signal)', marginLeft: '4px' }}>{prediction.trim() || '—'}</strong>
                </p>
              </div>
            </div>

            <div style={{ display: 'flex', gap: 'var(--space-md)', marginBottom: 'var(--space-lg)' }}>
              <span aria-hidden="true" style={{ color: 'var(--text-tertiary)', fontSize: '0.75rem', fontFamily: 'var(--font-display)', flexShrink: 0, width: 16 }}>✅</span>
              <div>
                <p style={{ margin: '0 0 var(--space-xs)', color: 'var(--text-secondary)', fontSize: '0.9375rem' }}>
                  Actual value:
                  <strong style={{ color: 'var(--signal)', marginLeft: '4px' }}>{actualValue}</strong>
                </p>
              </div>
            </div>

            <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              Why
            </p>
            <Markdown components={markdownComponents}>{explanation}</Markdown>
          </div>
          <div style={{ marginTop: 'var(--space-lg)' }}>
            <TryAgainButton onClick={reset} />
          </div>
        </div>
      )}
    </div>
  );
}


/* ══════════════════════════════════════════════════════════════
   8. PromptBuild — construct a coding prompt field-by-field with live preview
   ══════════════════════════════════════════════════════════════ */
export interface PromptField {
  key: string;
  question: string;
  options: FlowOption[];
  correctValue: string;
  feedback: Record<string, string>;
}

export interface PromptBuildProps {
  intro: string; // markdown
  fields: PromptField[];
  synthesis: string; // markdown
}

export function PromptBuild({ intro, fields, synthesis }: PromptBuildProps) {
  const [fieldIndex, setFieldIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [feedbackGiven, setFeedbackGiven] = useState(false);

  const handleSelect = (value: string) => {
    setAnswers(prev => ({ ...prev, [fields[fieldIndex].key]: value }));
    setFeedbackGiven(true);
  };

  const continueToNext = () => {
    if (fieldIndex < fields.length - 1) {
      setFieldIndex(prev => prev + 1);
      setFeedbackGiven(false);
    }
  };

  function reset() {
    setFieldIndex(0);
    setAnswers({});
    setFeedbackGiven(false);
  }

  const isLastField = fieldIndex === fields.length - 1;

  // Show synthesis panel only when all fields have been answered
  const allAnswered = Object.keys(answers).length === fields.length;

  /* Same focus contract as BuildIt — see the comment there for why the
   * per-field feedback hook is declared after the synthesis hook. */
  const synthesisRef = useRevealFocus<HTMLDivElement>(allAnswered);
  const fieldFeedbackRef = useRevealFocus<HTMLDivElement>(feedbackGiven);
  const promptRef = useReturnFocus<HTMLDivElement>(fieldIndex === 0 && !feedbackGiven);

  // Build the live preview prompt string (showing only answered fields in order)
  const buildPromptString = () => {
    const answeredFields = fields.filter((field) => answers[field.key] !== undefined);
    const lines = answeredFields.map((field) => answers[field.key]);
    if (lines.length === 0) return "";
    return lines.join('\n\n');
  };

  const currentField = fields[fieldIndex];

  return (
    <div style={{ border: '1px solid var(--bg-border)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginBottom: 'var(--space-xl)' }}>
      {/* Intro Panel */}
      <div style={{ background: 'rgba(201,168,76,0.07)', padding: 'var(--space-lg) var(--space-xl)' }}>
        <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">💬</span>
          <div ref={promptRef} tabIndex={-1} style={questionBlockFocusStyle}>
            <div style={{ color: 'var(--text-primary)', fontSize: '0.9375rem', lineHeight: 1.7, marginBottom: 'var(--space-md)' }}>
              <Markdown components={markdownComponents}>{intro}</Markdown>
            </div>

            {/* Live Preview Prompt Block */}
            {fields.length > 0 && (
              <pre
                aria-live="polite"
                aria-label="Live preview of the prompt you're building"
                style={{
                  fontFamily: 'var(--font-code)',
                  background: 'var(--bg-elevated)',
                  padding: 'var(--space-md)',
                  borderRadius: 'var(--radius-sm)',
                  overflowX: 'auto',
                  fontSize: '0.75rem',
                  whiteSpace: 'pre-wrap',
                  margin: '0 0 var(--space-lg)',
                }}
              >
                <code>{buildPromptString() || "Start building your prompt... (no fields answered yet)"}</code>
              </pre>
            )}

            {/* Field Construction Area */}
            <div style={{ marginTop: 'var(--space-md)' }}>
              {fieldIndex < fields.length && (
                <div>
                  <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', fontWeight: 600, margin: '0 0 var(--space-lg)' }}>
                    Field {fieldIndex + 1} of {fields.length}: {currentField.question}
                  </p>

                  {!feedbackGiven && (
                    <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
                      {currentField.options.map((option) => (
                        <button key={option.value} onClick={() => handleSelect(option.value)} style={optionButtonStyle}>
                          {option.label}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Feedback Panel */}
            {feedbackGiven && (
              <div
                ref={fieldFeedbackRef}
                tabIndex={-1}
                aria-live="polite"
                style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', marginTop: 'var(--space-lg)', background: answers[currentField.key] === currentField.correctValue ? 'rgba(90,158,106,0.05)' : 'rgba(196,107,58,0.05)' }}
              >
                <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
                  <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">{answers[currentField.key] === currentField.correctValue ? '✓' : '→'}</span>
                  <div style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
                    <Verdict correct={answers[currentField.key] === currentField.correctValue} />
                    <Markdown components={markdownComponents}>{currentField.feedback[answers[currentField.key]] ?? ''}</Markdown>
                  </div>
                </div>

                {!isLastField && (
                  <button onClick={continueToNext} style={{ ...primaryActionButtonStyle, marginTop: 'var(--space-lg)' }}>
                    Next field →
                  </button>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Synthesis Panel - shown only when all fields are answered */}
      {allAnswered && (
        <div ref={synthesisRef} tabIndex={-1} style={{ ...revealPanelFocusStyle, padding: 'var(--space-lg) var(--space-xl)', background: 'rgba(90,140,196,0.06)' }}>
          <div style={{ display: 'flex', gap: 'var(--space-md)', alignItems: 'flex-start' }}>
            <span style={{ fontSize: '1.125rem', flexShrink: 0 }} aria-hidden="true">✨</span>
            <div aria-live="polite" style={{ color: 'var(--text-secondary)', fontSize: '0.9375rem', lineHeight: 1.7 }}>
              <p style={{ margin: '0 0 var(--space-xs)', fontWeight: 600, color: 'var(--signal)', fontFamily: 'var(--font-display)', fontSize: '0.6875rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Your complete prompt</p>

              <pre
                style={{
                  fontFamily: 'var(--font-code)',
                  background: 'var(--bg-elevated)',
                  padding: 'var(--space-md)',
                  borderRadius: 'var(--radius-sm)',
                  overflowX: 'auto',
                  fontSize: '0.75rem',
                  whiteSpace: 'pre-wrap',
                  margin: '0 0 var(--space-lg)',
                }}
              >
                <code>{buildPromptString()}</code>
              </pre>

              <Markdown components={markdownComponents}>{synthesis}</Markdown>
            </div>
          </div>
          <div style={{ marginTop: 'var(--space-lg)' }}>
            <TryAgainButton onClick={reset} />
          </div>
        </div>
      )}
    </div>
  );
}
