#!/usr/bin/env bash
# Bedcoders Manual Deploy Approval
# Run this before every production deployment.
# Generates a signed deploy-approval.json that preflight-check.sh validates.

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

APPROVAL_FILE="$(dirname "$0")/../deploy-approval.json"
PREFLIGHT="$(dirname "$0")/preflight-check.sh"

echo ""
echo -e "${BOLD}=== Bedcoders Deploy Approval Gate ===${NC}"
echo -e "${YELLOW}Decisions locked: 2026-04-11. You are about to deploy to production.${NC}"
echo ""

# Run preflight first
echo "Running preflight checks..."
echo ""
if ! BEDCODERS_APPROVING=1 bash "$PREFLIGHT"; then
  echo ""
  echo -e "${RED}Preflight failed. Fix issues before approving a deploy.${NC}"
  exit 1
fi

echo ""
echo -e "${BOLD}Preflight passed.${NC}"
echo ""
echo "What is the reason for this deployment?"
echo -e "${YELLOW}(Be specific — this is logged permanently)${NC}"
read -r REASON

if [ -z "$REASON" ]; then
  echo -e "${RED}Reason cannot be empty.${NC}"
  exit 1
fi

echo ""
echo -e "${BOLD}Summary:${NC}"
echo "  Reason: $REASON"
echo "  Approver: $(whoami)@$(hostname)"
echo "  Time: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
echo ""
echo -e "${RED}${BOLD}Type DEPLOY to confirm and unlock the build:${NC}"
read -r CONFIRM

if [ "$CONFIRM" != "DEPLOY" ]; then
  echo -e "${RED}Deploy cancelled. You must type exactly: DEPLOY${NC}"
  exit 1
fi

# Write approval file (expires in 2 hours)
APPROVED_AT=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
EXPIRES_AT=$(date -u -v+2H '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || date -u -d '+2 hours' '+%Y-%m-%dT%H:%M:%SZ')
APPROVER="$(whoami)@$(hostname)"

cat > "$APPROVAL_FILE" <<EOF
{
  "approved": true,
  "approved_by": "$APPROVER",
  "approved_at": "$APPROVED_AT",
  "reason": "$REASON",
  "expires_at": "$EXPIRES_AT",
  "_note": "Auto-generated by approve-deploy.sh. Expires 2 hours after approval."
}
EOF

echo ""
echo -e "${GREEN}${BOLD}Deploy approved. Build unlocked for 2 hours.${NC}"
echo -e "${GREEN}Now run: npm run build${NC}"
echo ""
